//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoW.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        public Challenge()
        {
            this.ChallegeDays = new HashSet<ChallegeDay>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.TimeSpan> WakeUpTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> DonationId { get; set; }
        public Nullable<int> DonationAmount { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<ChallegeDay> ChallegeDays { get; set; }
        public virtual Donation Donation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
