//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoW.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public Donation()
        {
            this.Challenges = new HashSet<Challenge>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IconUrl { get; set; }
    
        public virtual ICollection<Challenge> Challenges { get; set; }
    }
}
