//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoW.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ChallengeId { get; set; }
        public string Text { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual User User { get; set; }
    }
}
