//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoW.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ChallegeDays = new HashSet<ChallegeDay>();
            this.Challenges = new HashSet<Challenge>();
            this.Messages = new HashSet<Message>();
            this.Socials = new HashSet<Social>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<ChallegeDay> ChallegeDays { get; set; }
        public virtual ICollection<Challenge> Challenges { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Social> Socials { get; set; }
    }
}
