//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoW.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WakeOrWasteEntities : DbContext
    {
        public WakeOrWasteEntities()
            : base("name=WakeOrWasteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChallegeDay> ChallegeDays { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
